# Generated by Django 5.0.14 on 2025-06-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_seat_chart_id_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['date', 'train']},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='arrival',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Journey Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='departure',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='date',
            field=models.DateField(verbose_name='Journey Date'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='first_ac',
            field=models.PositiveIntegerField(default=0, verbose_name='1st AC Seats'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='second_ac',
            field=models.PositiveIntegerField(default=0, verbose_name='2nd AC Seats'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='sleeper',
            field=models.PositiveIntegerField(default=0, verbose_name='Sleeper Seats'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='third_ac',
            field=models.PositiveIntegerField(default=0, verbose_name='3rd AC Seats'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='station',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(verbose_name='Journey Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fare Amount'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.CharField(max_length=50, verbose_name='Passenger Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('1A', 'First AC'), ('2A', 'Second AC'), ('3A', 'Third AC'), ('SL', 'Sleeper')], max_length=3, verbose_name='Class Type'),
        ),
        migrations.AlterField(
            model_name='train',
            name='arrival',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure Time'),
        ),
        migrations.AlterField(
            model_name='train',
            name='dest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_dest', to='book.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance (Km)'),
        ),
        migrations.AlterField(
            model_name='train',
            name='duration_h',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration Hours'),
        ),
        migrations.AlterField(
            model_name='train',
            name='duration_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration Minutes'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Train Name'),
        ),
        migrations.AlterField(
            model_name='train',
            name='number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Train Number'),
        ),
        migrations.AlterField(
            model_name='train',
            name='return_train',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Return Train Number'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='train_source', to='book.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='train',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('train', 'station')},
        ),
        migrations.AlterUniqueTogether(
            name='seat_chart',
            unique_together={('train', 'date')},
        ),
    ]
