# Generated by Django 5.0.14 on 2025-06-19 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_station_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='seat_chart',
            options={'verbose_name': 'Seat Chart', 'verbose_name_plural': 'Seat Charts'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='train',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dest_schedule',
        ),
        migrations.RemoveField(
            model_name='train',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='train',
            name='type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_to', to='book.station'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arriving_tickets', to='book.schedule'),
        ),
        migrations.AddField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_trains', to='book.station'),
        ),
        migrations.AddField(
            model_name='train',
            name='train_type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day of Journey'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_schedules', to='book.station'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='book.train'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='date',
            field=models.DateField(verbose_name='Travel Date'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='first_ac',
            field=models.PositiveIntegerField(verbose_name='1st AC'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='second_ac',
            field=models.PositiveIntegerField(verbose_name='2nd AC'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='sleeper',
            field=models.PositiveIntegerField(verbose_name='Sleeper'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='third_ac',
            field=models.PositiveIntegerField(verbose_name='3rd AC'),
        ),
        migrations.AlterField(
            model_name='seat_chart',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_charts', to='book.train'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(verbose_name='Travel Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.PositiveIntegerField(verbose_name='Fare'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.CharField(max_length=20, verbose_name='Passenger Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_from', to='book.station'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_tickets', to='book.schedule'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='book.train'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('1A', 'First AC'), ('2A', 'Second AC'), ('3A', 'Third AC'), ('SL', 'Sleeper')], max_length=2, verbose_name='Coach Type'),
        ),
        migrations.AlterField(
            model_name='train',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='train',
            name='duration_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration Hours'),
        ),
        migrations.AlterField(
            model_name='train',
            name='duration_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duration Minutes'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='train',
            name='return_train',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Return Train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_trains', to='book.station'),
        ),
    ]
