# Generated by Django 5.0.14 on 2025-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_schedule_options_alter_seat_chart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='stop_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Stop Order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fare',
            field=models.PositiveIntegerField(default=0, verbose_name='Fare'),
        ),
    ]
